import java_cup.runtime.*;
import java.io.*;

parser code {:

    scanner s;

    static java.util.HashMap<String,Integer> tabela =
        new java.util.HashMap<>();

    static java.util.HashSet<String> constantes =
        new java.util.HashSet<>();

    static java.util.HashMap<String,Funcao> funcoes =
        new java.util.HashMap<>();

    boolean executar = true;

    static class Funcao {
        String nome;
        java.util.ArrayList<String> parametros;
        String corpo;
        Funcao(
            String nome,
            java.util.ArrayList<String> parametros,
            String corpo
        ){
            this.nome = nome;
            this.parametros = parametros;
            this.corpo = corpo;
        }
    }

    void executarFuncao(
        String nome,
        java.util.ArrayList<Integer> argumentos
    ){
        Funcao f = funcoes.get(nome);
        if(f == null){
            System.out.println(
                "Função não encontrada: " + nome
            );
            return;
        }
        String codigo = f.corpo;
    for(
        int i=0;
        i<f.parametros.size();
        i++
    ){
        codigo =
            codigo.replaceAll(
                "\\b" +
                f.parametros.get(i) +
                "\\b",
                argumentos.get(i).toString()
            );
    }

try{

    scanner novoScanner =
        new scanner(
            new java.io.StringReader(
                codigo
            )
        );

    parser novoParser =
        new parser(
            novoScanner
        );

    novoParser.tabela = this.tabela;
    novoParser.constantes = this.constantes;
    novoParser.funcoes = this.funcoes;
    novoParser.parse();

}
catch(Exception e){

    System.out.println(
        "Erro executando função."
    );

    e.printStackTrace();
}
}

    parser(scanner s){
        this.s=s;
    }

:}

scan with {: return s.next_token(); :};


terminal IF, ELSE, WHILE;
terminal RETURN, CONST, VAR;

terminal ADD, SUB, MULT, DIV;
terminal IGUAL, DIFERENTE;

terminal LPAREN, RPAREN;
terminal ASPA;

terminal String IDENT;
terminal Integer NUMERO;

terminal String ESPECIAL;
terminal String STRING;

non terminal programa;
non terminal bloco;
non terminal lista_comandos;
non terminal comando;

non terminal declaracao;
non terminal atribuicao;
non terminal consulta;

non terminal funcao;
non terminal chamada_funcao;
non terminal java.util.ArrayList parametros;
non terminal java.util.ArrayList argumentos;

non terminal estrutura_if;
non terminal estrutura_while;
non terminal Boolean condicao;

non terminal Integer expressao;

precedence left ADD, SUB;
precedence left MULT, DIV;

start with programa;

programa ::= lista_comandos
;

bloco ::= LPAREN lista_comandos RPAREN
;

lista_comandos ::=
        lista_comandos comando
      | comando
      ;

comando ::=
        declaracao
      | atribuicao
      | estrutura_if
      | estrutura_while
      | consulta
      | funcao
      | chamada_funcao
      | error
      {:
          System.out.println(
              "Comando inválido."
          );
      :}
      ;

declaracao ::=
        VAR IDENT:n {:
        if (executar){
        if(tabela.containsKey(n)){
            System.out.println(
                "Erro: variável já declarada: " + n
            );
        } else {
            tabela.put(n, null);
            System.out.println(
                "Variável declarada: " + n
            );
        }
        }
    :}
      | CONST IDENT:n {:
        if(tabela.containsKey(n)){
            System.out.println(
                "Erro: identificador já declarado: " + n
            );
        }
        else{
            tabela.put(n, null);
            constantes.add(n);

            System.out.println(
                "Constante declarada: " + n
            );
        }
:}
;

atribuicao ::=
    IDENT:n IGUAL expressao:v
    {:
        if(executar){
        if(!tabela.containsKey(n)){
            System.out.println(
                "Erro: identificador não declarado: " + n
            );
        }
        else if(constantes.contains(n) && tabela.get(n) != null){
            System.out.println(
                "Erro: constante não pode ser alterada: "
                + n
            );
        }
        else{
            tabela.put(n, v);
            System.out.println(
                "Atribuição feita: "
                + n + " = " + v
            );
        }
    }
    :}
;

estrutura_if ::=
    IF LPAREN condicao:c RPAREN
    {:
        executar = c;
    :}
    bloco
    ELSE
    {:
        executar = !c;
    :}
    bloco
    {:
        executar = true;
    :}
;

estrutura_while ::=
        WHILE LPAREN condicao:c RPAREN bloco {:
        while(c){
            System.out.println(
                "Loop enquanto a condição for verdadeira"
            );
        }
    :}
;

expressao ::=
      NUMERO:n
      {: RESULT = n; :}

    | IDENT:n
      {:
          Integer valor = tabela.get(n);
          RESULT = valor;
      :}

     | LPAREN expressao:e RPAREN
      {: RESULT = e; :}

    | expressao:e1 ADD expressao:e2
      {: RESULT = e1 + e2; :}

    | expressao:e1 SUB expressao:e2
      {: RESULT = e1 - e2; :}

    | expressao:e1 MULT expressao:e2
      {: RESULT = e1 * e2; :}

    | expressao:e1 DIV expressao:e2
      {: RESULT = e1 / e2; :}   
;

consulta ::=
    expressao:e
          {:
          if (executar){
            if (e == null) {
                System.out.println("Variável não inicializada ou expressão inválida.");
            } else {
                System.out.println("Resultado da consulta: " + e);
            }
          }
      :}
;

condicao ::=
    IDENT:n
    {:
        RESULT = tabela.containsKey(n);
    :}
    | NUMERO:n
    {:
        RESULT = true;
    :}
    | expressao:e1 IGUAL expressao:e2
    {:
        RESULT = e1.equals(e2);
    :}
    | expressao:e1 DIFERENTE expressao:e2
      {:
          RESULT = !e1.equals(e2);
      :}
;

funcao ::=
    ESPECIAL IDENT:n LPAREN parametros:p RPAREN STRING:corpo
    {:
        Funcao f =
            new Funcao(
                n,
                p,
                corpo
            );

        funcoes.put(n,f);

        System.out.println(
            "Função criada: " + n
        );
    :}
;

parametros ::=

      IDENT:n
      {:
          java.util.ArrayList<String> p =
              new java.util.ArrayList<>();

          p.add(n);

          RESULT = p;
      :}

    | parametros:p IDENT:n
      {:
          p.add(n);
          RESULT = p;
      :}

    | ESPECIAL
      {:
          RESULT = new java.util.ArrayList<>();
      :}
;

argumentos ::=
      expressao:e
      {:
          java.util.ArrayList<Integer> a =
              new java.util.ArrayList<>();
          a.add(e);
          RESULT = a;
      :}

    | argumentos:a expressao:e
      {:
          a.add(e);
          RESULT = a;
      :}
    | ESPECIAL
      {:
          RESULT = new java.util.ArrayList<>();
      :}
;

chamada_funcao ::=
    IDENT:n LPAREN argumentos:a RPAREN
    {:
        executarFuncao(n,a);
    :}
;